name: inception
services:
  mariadb:
    image: mariadb:inception
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    secrets:
      - db_root_password
      - db_password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: always

  wordpress:
    image: wordpress:inception
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    env_file:
      - .env
      - local.env
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
    restart: always

  nginx:
    image: nginx:inception
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html:ro
    networks:
      - inception
    ports:
      - "443:443"
    depends_on:
      - wordpress
    restart: always

volumes:
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_DIR}/mariadb

  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_DIR}/wordpress

networks:
  inception:
    name: inception
    driver: bridge

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt

  db_password:
    file: ../secrets/db_password.txt

  wp_admin_password:
    file: ../secrets/wp_admin_password.txt

  wp_user_password:
    file: ../secrets/wp_user_password.txt
